
package interfaz;
import cliente.ClienteRMI;
import modelo.Ticket;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Vladimir
 */
public class Interfaz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interfaz.class.getName());
    // Cliente RMI para comunicarse con el servidor
    private ClienteRMI cliente;
    
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
     
    initComponents();
    // Campos solo de lectura (solo muestran información)
numero_pendientes2.setEditable(false);
numero_en_proceso.setEditable(false);
numero_resuelto.setEditable(false);
numero_tecnicos_libres.setEditable(false);
    // 1. Evita que el usuario pueda cambiar el tamaño de la ventana
    setResizable(false); 
    
    // 2. Hace que la ventana tome el tamaño preferido de sus componentes
    pack(); 
    
    // 3. Centra la ventana en la pantalla (debe ir después de pack o de definir el tamaño)
    setLocationRelativeTo(null);
    // Conectamos con el servidor RMI
    cliente = new ClienteRMI();
    actualizarEstadoSistema();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        titulo_pendidientes = new javax.swing.JLabel();
        titulo_proceso = new javax.swing.JLabel();
        titulo_resuelto = new javax.swing.JLabel();
        titulo_tecnico_libre = new javax.swing.JLabel();
        numero_en_proceso = new javax.swing.JTextField();
        numero_resuelto = new javax.swing.JTextField();
        numero_pendientes2 = new javax.swing.JTextField();
        numero_tecnicos_libres = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablapara_ide_cliente_prioridad_estado_tecnico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        boton_Actualizar = new javax.swing.JButton();
        boton_Tomar = new javax.swing.JButton();
        boton_resolver = new javax.swing.JButton();
        boton_ver_detalle = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        espacio_para_escribir_nombre_cliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Area_para_escribir_prioridad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Area_para_escribir_descripcion = new javax.swing.JTextField();
        boton_crear = new javax.swing.JButton();
        boton_limpiar = new javax.swing.JButton();
        Boton_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Estado del sistema");

        titulo_pendidientes.setText("Pendientes:");

        titulo_proceso.setText("En proceso:");

        titulo_resuelto.setText("Resueltos:");

        titulo_tecnico_libre.setText("Técnicos Libres:");

        numero_en_proceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_en_procesoActionPerformed(evt);
            }
        });

        numero_resuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_resueltoActionPerformed(evt);
            }
        });

        numero_pendientes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_pendientes2ActionPerformed(evt);
            }
        });

        numero_tecnicos_libres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero_tecnicos_libresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(titulo_pendidientes)
                        .addGap(5, 5, 5)
                        .addComponent(numero_pendientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo_proceso)
                        .addGap(1, 1, 1)
                        .addComponent(numero_en_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(titulo_resuelto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero_resuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(titulo_tecnico_libre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numero_tecnicos_libres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero_en_proceso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero_pendientes2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo_resuelto)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numero_resuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numero_tecnicos_libres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(titulo_proceso)
                    .addComponent(titulo_pendidientes)
                    .addComponent(titulo_tecnico_libre))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        tablapara_ide_cliente_prioridad_estado_tecnico.setBackground(new java.awt.Color(204, 204, 255));
        tablapara_ide_cliente_prioridad_estado_tecnico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablapara_ide_cliente_prioridad_estado_tecnico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Prioridad", "Estado", "Tecnico"
            }
        ));
        jScrollPane1.setViewportView(tablapara_ide_cliente_prioridad_estado_tecnico);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Tickets");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Acciones");

        boton_Actualizar.setBackground(new java.awt.Color(153, 153, 255));
        boton_Actualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton_Actualizar.setForeground(new java.awt.Color(255, 255, 255));
        boton_Actualizar.setText("Actualizar");
        boton_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ActualizarActionPerformed(evt);
            }
        });

        boton_Tomar.setBackground(new java.awt.Color(153, 153, 255));
        boton_Tomar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_Tomar.setForeground(new java.awt.Color(255, 255, 255));
        boton_Tomar.setText("Tomar");
        boton_Tomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_TomarActionPerformed(evt);
            }
        });

        boton_resolver.setBackground(new java.awt.Color(153, 153, 255));
        boton_resolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_resolver.setForeground(new java.awt.Color(255, 255, 255));
        boton_resolver.setText("Resolver");
        boton_resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_resolverActionPerformed(evt);
            }
        });

        boton_ver_detalle.setBackground(new java.awt.Color(153, 153, 255));
        boton_ver_detalle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_ver_detalle.setForeground(new java.awt.Color(255, 255, 255));
        boton_ver_detalle.setText("Ver detalle");
        boton_ver_detalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_ver_detalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(boton_Actualizar)
                        .addGap(33, 33, 33)
                        .addComponent(boton_Tomar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(boton_resolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton_ver_detalle))
                    .addComponent(jLabel3))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_Tomar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_resolver, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton_ver_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Crear tickets");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Cliente :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Prioridad:");

        Area_para_escribir_prioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area_para_escribir_prioridadActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Descripcion:");

        boton_crear.setBackground(new java.awt.Color(0, 153, 102));
        boton_crear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_crear.setForeground(new java.awt.Color(255, 255, 255));
        boton_crear.setText("Crear");
        boton_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearActionPerformed(evt);
            }
        });

        boton_limpiar.setBackground(new java.awt.Color(255, 102, 0));
        boton_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        boton_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        boton_limpiar.setText("Limpiar");
        boton_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_limpiarActionPerformed(evt);
            }
        });

        Boton_salir.setBackground(new java.awt.Color(153, 153, 153));
        Boton_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Boton_salir.setForeground(new java.awt.Color(255, 255, 255));
        Boton_salir.setText("Salir");
        Boton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(espacio_para_escribir_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Area_para_escribir_prioridad))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Area_para_escribir_descripcion))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boton_limpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Boton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(espacio_para_escribir_nombre_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Area_para_escribir_prioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Area_para_escribir_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_salir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(boton_crear, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(boton_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ActualizarActionPerformed
      List<Ticket> lista = cliente.listarTickets();
      if (lista == null) {
    JOptionPane.showMessageDialog(this, "No se pudo conectar con el servidor. ¿Está ServidorMain arrancado?");
    return;
}

    DefaultTableModel modelo = (DefaultTableModel) tablapara_ide_cliente_prioridad_estado_tecnico.getModel();
    modelo.setRowCount(0);

    for (Ticket t : lista) {
        Object[] fila = {
            t.getId(),
            t.getCliente(),
            t.getPrioridad(),
            t.getEstado(),
            t.getTecnicoAsignado()
        };
        modelo.addRow(fila);
    }
    ////**********************
    // AQUÍ SÍ LLAMAMOS A LAS ESTADÍSTICAS
    actualizarEstadoSistema();
    }//GEN-LAST:event_boton_ActualizarActionPerformed

    private void boton_TomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_TomarActionPerformed
          int fila = tablapara_ide_cliente_prioridad_estado_tecnico.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un ticket");
        return;
    }

    // COMPROBAR SI HAY TÉCNICOS LIBRES
    if (numero_tecnicos_libres.getText().equals("0")) {
        JOptionPane.showMessageDialog(
            this,
            "No hay técnicos disponibles por el momento",
            "Aviso",
            JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Pedimos el nombre del técnico
    String tecnico = JOptionPane.showInputDialog(this, "Nombre del técnico:");
    if (tecnico == null || tecnico.isEmpty()) {
        return;
    }

    //  COMPROBAR SI ESE TÉCNICO YA ESTÁ OCUPADO
    for (int i = 0; i < tablapara_ide_cliente_prioridad_estado_tecnico.getRowCount(); i++) {

        String tecnicoTabla = String.valueOf(
            tablapara_ide_cliente_prioridad_estado_tecnico.getValueAt(i, 4)
        );
        String estadoTabla = String.valueOf(
            tablapara_ide_cliente_prioridad_estado_tecnico.getValueAt(i, 3)
        );

        if (tecnico.equals(tecnicoTabla) && estadoTabla.equals("EN_PROCESO")) {
            JOptionPane.showMessageDialog(
                this,
                "Ese técnico no está disponible en este momento",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }
    }

    //  SOLO AQUÍ se toma el ticket
    int id = (int) tablapara_ide_cliente_prioridad_estado_tecnico.getValueAt(fila, 0);
    cliente.tomarTicket(id, tecnico);

    // Actualizamos la interfaz
    boton_ActualizarActionPerformed(null);
    actualizarEstadoSistema();
    
    }//GEN-LAST:event_boton_TomarActionPerformed

    private void Area_para_escribir_prioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area_para_escribir_prioridadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area_para_escribir_prioridadActionPerformed

    private void boton_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearActionPerformed
     String nombre = espacio_para_escribir_nombre_cliente.getText();
    String prioridad = Area_para_escribir_prioridad.getText();
    String descripcion = Area_para_escribir_descripcion.getText();

    if (nombre.isEmpty() || prioridad.isEmpty() || descripcion.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Rellena todos los campos");
        return;
    }

    // 1️⃣ Crear el ticket
    cliente.crearTicket(nombre, descripcion, prioridad);

    JOptionPane.showMessageDialog(this, "Ticket creado correctamente");

    // 2️⃣ Actualizar tabla y estadísticas
    boton_ActualizarActionPerformed(null);
    actualizarEstadoSistema();

    // 3️⃣ Limpiar campos
    espacio_para_escribir_nombre_cliente.setText("");
    Area_para_escribir_prioridad.setText("");
    Area_para_escribir_descripcion.setText("");

    }//GEN-LAST:event_boton_crearActionPerformed

    private void boton_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_limpiarActionPerformed
        espacio_para_escribir_nombre_cliente.setText("");
    Area_para_escribir_prioridad.setText("");
    Area_para_escribir_descripcion.setText("");
    }//GEN-LAST:event_boton_limpiarActionPerformed

    private void Boton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_salirActionPerformed
            System.exit(0);
    }//GEN-LAST:event_Boton_salirActionPerformed

    private void boton_resolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_resolverActionPerformed
        int fila = tablapara_ide_cliente_prioridad_estado_tecnico.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un ticket");
        return;
    }

    int id = (int) tablapara_ide_cliente_prioridad_estado_tecnico.getValueAt(fila, 0);
    cliente.resolverTicket(id);

    JOptionPane.showMessageDialog(this, "Ticket resuelto");
    
    // ACTUALIZA LA TABLA AUTOMÁTICAMENTE
boton_ActualizarActionPerformed(null);
actualizarEstadoSistema();
    }//GEN-LAST:event_boton_resolverActionPerformed
   
    private void boton_ver_detalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_ver_detalleActionPerformed
         int fila = tablapara_ide_cliente_prioridad_estado_tecnico.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona un ticket");
        return;
    }

    int id = (int) tablapara_ide_cliente_prioridad_estado_tecnico.getValueAt(fila, 0);
    List<String> historial = cliente.obtenerHistorialTicket(id);

    String texto = "";
    for (String h : historial) {
        texto += h + "\n";
    }

    JOptionPane.showMessageDialog(this, texto, "Historial del Ticket", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_boton_ver_detalleActionPerformed

    private void numero_en_procesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_en_procesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_en_procesoActionPerformed

    private void numero_resueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_resueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_resueltoActionPerformed

    private void numero_pendientes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_pendientes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_pendientes2ActionPerformed

    private void numero_tecnicos_libresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero_tecnicos_libresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero_tecnicos_libresActionPerformed
// Este método rellena los campos del "Estado del sistema"
// Este método rellena los campos del "Estado del sistema"
private void actualizarEstadoSistema() {

    // Pedimos al servidor las estadísticas
    String texto = cliente.obtenerEstadisticas();

    if (texto == null || texto.isEmpty()) {
        return;
    }

    // Formato recibido:
    // Pendientes: X | En proceso: Y | Resueltos: Z | Técnicos libres: W
    try {
        String[] partes = texto.split("\\|");

        // Pendientes
        numero_pendientes2.setText(
            partes[0].replace("Pendientes:", "").trim()
        );

        // En proceso
        numero_en_proceso.setText(
            partes[1].replace("En proceso:", "").trim()
        );

        // Resueltos
        numero_resuelto.setText(
            partes[2].replace("Resueltos:", "").trim()
        );

        // Técnicos libres
        numero_tecnicos_libres.setText(
            partes[3].replace("Técnicos libres:", "").trim()
        );

    } catch (Exception e) {
        System.out.println("Error al actualizar el estado del sistema");
    }
}


    
    public static void main(String[] args) {

    /*
     * Arrancamos la interfaz gráfica.
     
     */
    java.awt.EventQueue.invokeLater(() -> {
        new Interfaz().setVisible(true);
    });
    
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Area_para_escribir_descripcion;
    private javax.swing.JTextField Area_para_escribir_prioridad;
    private javax.swing.JButton Boton_salir;
    private javax.swing.JButton boton_Actualizar;
    private javax.swing.JButton boton_Tomar;
    private javax.swing.JButton boton_crear;
    private javax.swing.JButton boton_limpiar;
    private javax.swing.JButton boton_resolver;
    private javax.swing.JButton boton_ver_detalle;
    private javax.swing.JTextField espacio_para_escribir_nombre_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numero_en_proceso;
    private javax.swing.JTextField numero_pendientes2;
    private javax.swing.JTextField numero_resuelto;
    private javax.swing.JTextField numero_tecnicos_libres;
    private javax.swing.JTable tablapara_ide_cliente_prioridad_estado_tecnico;
    private javax.swing.JLabel titulo_pendidientes;
    private javax.swing.JLabel titulo_proceso;
    private javax.swing.JLabel titulo_resuelto;
    private javax.swing.JLabel titulo_tecnico_libre;
    // End of variables declaration//GEN-END:variables


}
